#!/usr/bin/env python3

import http.server
import ssl
import argparse

parser = argparse.ArgumentParser(
    prog='httpsd',
    description='Simple https server for testing TLS configuration'
)

parser.add_argument('--certfile', type=str, default="cert.pem")
parser.add_argument('--keyfile', type=str, default="key.pem")
parser.add_argument('--port', type=int, default=4443)
parser.add_argument('--address', type=str, default="localhost")

args = parser.parse_args()

keyfile = args.keyfile
certfile = args.certfile
port = args.port
address = args.address

server_address = (address, port)
httpd = http.server.HTTPServer(
    server_address, http.server.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket(httpd.socket,
                               server_side=True,
                               certfile=certfile,
                               keyfile=keyfile,
                               ssl_version=ssl.PROTOCOL_TLS)


print("starting https server")

httpd.serve_forever()
